### ISSUE TITLE
The pixel values of the images input to the network are in the range of 0-1 or 0-255?

### ISSUE THREAD

**Issue by Full-Adder** [atsiami/STAViS#18]
I see in opts.py

parser.add_argument(
        '--norm_value',
        default=1,
        type=int,
        help=
        'If 1, range of inputs is [0-255]. If 255, range of inputs is [0-1].')

and there is no change in main.py or run*.sh, so after ToTensor(opt.norm_value), the value of img is [0-255]?

**Comment by Full-Adder** [comment]
I have an other question, the audio is about 16bit which means the max value of it is 2^16, but in audio dataset : 
audiowav = audiowav * (2 ** -23)
is it right?

**Comment by pkoutras** [comment]
Regarding the first question, the img-tensor is normalised using the :https://github.com/atsiami/STAViS/blob/d0fd9df89aa3b6bf85b93a1570eb824456a704de/spatial_transforms.py#L86
by subtracting the mean-value computed from the `activitynet` dataset but not any std-value:
https://github.com/atsiami/STAViS/blob/d0fd9df89aa3b6bf85b93a1570eb824456a704de/mean.py#L4

**Comment by pkoutras** [comment]
Regarding the second question we followed the same approach as in the Soundnet paper:
```
sound = audio.load('file.mp3'):mul(2^-23):view(1,1,-1,1):cuda()
predictions = net:forward(sound)
```
http://soundnet.csail.mit.edu/

in order to get the range in `[-256, 256]` as described in the paper:

"We also scaled the waveform to be in the range [−256, 256]. We did not need to
subtract the mean because it was naturally near zero already."
