### ISSUE TITLE
The eye_tracks.mat in data/annotation

### ISSUE THREAD

**Issue by Nanjo-Naoto** [atsiami/STAViS#4]
In AVAD dataset, the eye_tracks.mat has the numbers of frames cells with tens of number pairs in each cell. However, in other 5 datasets, the eye_track.mat files only have tens of cells and there are the number of frames number pairs in each cell. Why it is special only in AVAD dataset and what's the difference between these 2 kinds of mat files? Will it influence the train and val result?

By the way, I want to know how the eyeMap is generated and why the fixMap_{%05d}.mat files are filled with zeros?

**Comment by atsiami** [comment]
We have prepossessed all datasets to obtain the eyeMap and fixMap that are used in all the steps of training and evaluation (the eye_tracks.mat are not used and are given just for completeness). The fixMap has ones as values at the pixels that are fixation points and zeros elsewhere. The eyeMap is created by the fixMap by centering a Gaussian at each fixation point following the standard approach in the literature. Note that in all the evaluations (both with our models and the state-of-the-art method) we have used our preprocessed maps.

Regarding the AVAD, the original database creators provide directly the fixMap rather than the eye_tracks for each subject. We convert them to eye_tracks just for completeness and practically it was more easy to have the number of frames at the cell level.

**Comment by Nanjo-Naoto** [comment]
Thankyou，and I also found in modes/resnet.py line 277 is "crop_h, crop_h = int(x.size()[-2]), int(x.size()[-1])" and all of the following references are both h. Is it a mistake of "crop_h, crop_w"? Because I found in other place for example the forward function in class av_module, it is "crop_h, crop_w"

**Comment by pkoutras** [comment]
Thank you very much for pointing this issue. It was a mistake and now it is fixed. However, since the employed crops are always square (i.e. 112x112), all the results (training and testing) in our models remain the same.
